
package isp.lab9.exercise3;

import java.util.Map;
import javax.swing.JOptionPane;

public class MasterGUI extends javax.swing.JFrame {

    /**
     * Creates new form MasterInterface
     */
     static DoorLockController ctrl;
    
    public MasterGUI(DoorLockController ctrl) {
        this.ctrl=ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeMenuButton = new javax.swing.JButton();
        tenantNameTextField = new javax.swing.JTextField();
        tenantPasswordTextField = new javax.swing.JTextField();
        tenantNameLabel = new javax.swing.JLabel();
        tenantPasswordLabel = new javax.swing.JLabel();
        insertTenantButton = new javax.swing.JButton();
        removeTenantButton = new javax.swing.JButton();
        showTenantsButton = new javax.swing.JButton();

        closeMenuButton.setText("Close Master Menu");
        closeMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuButtonActionPerformed(evt);
            }
        });

        tenantNameLabel.setText("Tenant name");

        tenantPasswordLabel.setText("Tenant password");

        insertTenantButton.setText("Insert new tenant");
        insertTenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTenantActionPerformed(evt);
            }
        });

        removeTenantButton.setText("Remove tenant");
        removeTenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTenantButtonActionPerformed(evt);
            }
        });

        showTenantsButton.setText("Show all tenants");
        showTenantsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTenantsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(insertTenantButton)
                        .addGap(82, 82, 82)
                        .addComponent(removeTenantButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tenantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenantPasswordLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tenantPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(tenantNameTextField))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showTenantsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenantNameLabel)
                    .addComponent(tenantNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenantPasswordLabel)
                    .addComponent(tenantPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertTenantButton)
                    .addComponent(removeTenantButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(showTenantsButton)
                .addGap(18, 18, 18)
                .addComponent(closeMenuButton)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeMenuButtonActionPerformed

    private void insertTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTenantActionPerformed
        String pin=tenantPasswordTextField.getText();
        String name=tenantNameTextField.getText();
        if (pin.equals("") || name.equals("")) JOptionPane.showMessageDialog(null, "Insert valid name and pin!");
        else{
         try {
             ctrl.addTenant(pin, name);
             JOptionPane.showMessageDialog(null, "Tenant added succesfully!");
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Tenant already exists!");
         }
        }
    }//GEN-LAST:event_insertTenantActionPerformed

    private void removeTenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTenantButtonActionPerformed
        String name=tenantNameTextField.getText();
         try {
             ctrl.removeTenant(name);
             JOptionPane.showMessageDialog(null, "Tenant removed succesfully!");
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Tenant doesn't exists!");
         }
    }//GEN-LAST:event_removeTenantButtonActionPerformed

    private void showTenantsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTenantsButtonActionPerformed
         try {
             Map<Tenant, AccessKey> tenantsMap=ctrl.getTenants();
             TenantGUI tenantInterface=new TenantGUI(tenantsMap);
             tenantInterface.setVisible(true);
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Tenant list is empty");
         }
    }//GEN-LAST:event_showTenantsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeMenuButton;
    private javax.swing.JButton insertTenantButton;
    private javax.swing.JButton removeTenantButton;
    private javax.swing.JButton showTenantsButton;
    private javax.swing.JLabel tenantNameLabel;
    private javax.swing.JTextField tenantNameTextField;
    private javax.swing.JLabel tenantPasswordLabel;
    private javax.swing.JTextField tenantPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
